AWSTemplateFormatVersion: 2010-09-09
Parameters:
    InstanceType:
        Type: String
        Default: t1.micro
        Description: Instance Type

    AMI:
        Type: String
        Description: Select AMI for your region https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html

    AutoscaleInstances:
        Type: Number
        Default: 2
        Description: Numer of instances in Autoscaling group

Resources:

    MyLaunchConfig:
        Type: AWS::AutoScaling::LaunchConfiguration
        Properties:
          ImageId: !Ref AMI
          InstanceType: !Ref InstanceType



    MyAutoscalingGroup:
        Type: AWS::AutoScaling::AutoScalingGroup
        Properties:
          AvailabilityZones: !GetAZs ''
          LaunchConfigurationName: !Ref MyLaunchConfig
          MinSize: 1
          MaxSize: 6
          DesiredCapacity: !Ref AutoscaleInstances

    AutoscaleToRoute53Role:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Principal: {Service: [lambda.amazonaws.com]}
              Action: ['sts:AssumeRole']
          Path: /
          ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
          Policies:
          - PolicyName: S3Policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Sid: AccessToEC2andRoute53
                  Action:
                    - 'EC2:*'
                    - 'autoscaling:*'
                    - 'route53:*'
                  Resource: '*'
